In [1]:
import torch
import numpy as np

# Bài 1: Tạo Tensor cơ bản

In [4]:
import torch
a= torch.tensor([[1,2,3],
                 [4,5,6]],
                 dtype=torch.int32
                 )
print("tensor a: ")
print(a)
print("kich thuoc: ", a.shape)
print("so chieu: ", a.ndim)
print("kieu du lieu: ", a.dtype)


tensor a: 
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
kich thuoc:  torch.Size([2, 3])
so chieu:  2
kieu du lieu:  torch.int32


## Nhận xét
 - tensor a có kích thước 2x3
 - tensor a có 2 chiều
 - kiểu dữ liệu của tensor a là torch.int32


# Bài 2: Tạo các Tensor thường dùng

In [5]:
a= torch.rand(3,4)
b= torch.randn(3,4)
c= torch.zeros( 2,3)
d= torch.ones(2,3)
e= torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.0475, 0.5983, 0.2359, 0.0296],
        [0.2341, 0.8856, 0.4388, 0.5423],
        [0.2649, 0.2759, 0.6920, 0.6793]])
tensor([[-0.4591,  0.9306, -0.2033, -0.5048],
        [ 1.5559, -0.2219,  1.0273,  0.4776],
        [ 0.9066,  0.4367, -0.7814,  1.2985]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [13]:

f= torch.full((5,5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Nhận xét
- torch.rand() tạo số ngẫu nhiên theo phân phối đều từ 0 đến 1
- torch.randn() tạo số ngẫu nhiên theo phân phối chuẩn
- torch.zeros() tạo tensor toàn số 0
- torch.ones() tạo tensor toàn số 1
- torch.eye() tạo ma trận đơn vị
- torch.full((5,5), 10) tạo tensor 5x5 chứa toàn giá trị 10 

# Bài 3: Kiểm tra thông tin tensor

In [10]:
a= torch.zeros(2,3,4)
print("tensor: ")
print(a)
print("shape: ", a.shape)
print("size: ", a.size())
print("number of dimesions: ", a.ndim)
print("data type: ", a.dtype)


tensor: 
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
shape:  torch.Size([2, 3, 4])
size:  torch.Size([2, 3, 4])
number of dimesions:  3
data type:  torch.float32


## Nhận xét
- torch.size([2,3,4]) cho biết tensor có 3 chiều với kích thước lần lượt là 2,3,4

# Bài 4: Slicing và Indexing

In [11]:
a= torch.rand(3,4,5)
print("original tensor: ")
print(a)

print("\ntensor a[1]: ")
print(a[1])

print("\ntensor a[1:, 2:4] :")
print(a[1:, 2:4])

original tensor: 
tensor([[[0.6304, 0.2268, 0.3016, 0.7541, 0.2522],
         [0.8935, 0.2384, 0.1865, 0.8930, 0.7227],
         [0.3451, 0.1954, 0.5649, 0.0180, 0.4691],
         [0.0237, 0.5415, 0.8359, 0.9143, 0.7361]],

        [[0.9237, 0.6469, 0.0206, 0.5928, 0.8579],
         [0.4345, 0.5813, 0.7016, 0.1746, 0.3129],
         [0.3386, 0.7878, 0.9704, 0.6003, 0.4886],
         [0.9536, 0.2460, 0.4655, 0.6720, 0.5237]],

        [[0.2942, 0.9279, 0.9368, 0.5074, 0.9350],
         [0.6005, 0.2400, 0.4170, 0.6237, 0.0019],
         [0.6784, 0.2395, 0.2536, 0.4191, 0.3135],
         [0.7178, 0.1046, 0.7769, 0.2343, 0.8045]]])

tensor a[1]: 
tensor([[0.9237, 0.6469, 0.0206, 0.5928, 0.8579],
        [0.4345, 0.5813, 0.7016, 0.1746, 0.3129],
        [0.3386, 0.7878, 0.9704, 0.6003, 0.4886],
        [0.9536, 0.2460, 0.4655, 0.6720, 0.5237]])

tensor a[1:, 2:4] :
tensor([[[0.3386, 0.7878, 0.9704, 0.6003, 0.4886],
         [0.9536, 0.2460, 0.4655, 0.6720, 0.5237]],

        [[0.6784, 0.239

In [12]:
print("lay 2 phan tu cuoi tren chieu thu 3: ")
print(a[: , : , -2])

lay 2 phan tu cuoi tren chieu thu 3: 
tensor([[0.7541, 0.8930, 0.0180, 0.9143],
        [0.5928, 0.1746, 0.6003, 0.6720],
        [0.5074, 0.6237, 0.4191, 0.2343]])


## Nhận xét
- a có shape là torch.size([3,4,5])
- a[1] có shape là torch.size([4,5])
- a[1:, 2:4] có shape là torch.size([2,2,5])
- a[:, :, -2] là lấy 2 phần tử cuối trên chiều thứ 3

# Bài 5: Reshape và Flatten

In [15]:
a= torch.rand(3,4)
print("original: ")
print(a)

print("\nFlatten: ")
print(a.ravel())

print("\nReshape to 3x2x2: ")
print(a.reshape(3,2,2))

print("\nReshape thanh kich thuoc 2x6: ")
print(a.reshape(2,6))

print("\nSo phan tu ban dau: ", a.numel())
print("\nSo phan tu sau khi reshape 3x2x2: ", a.reshape(3,2,2).numel())
print("\nSo phan tu sau khi reshape 2x6: ", a.reshape(2,6).numel())

original: 
tensor([[0.9669, 0.2515, 0.4714, 0.4307],
        [0.0537, 0.7649, 0.6509, 0.5877],
        [0.9159, 0.8122, 0.6000, 0.8836]])

Flatten: 
tensor([0.9669, 0.2515, 0.4714, 0.4307, 0.0537, 0.7649, 0.6509, 0.5877, 0.9159,
        0.8122, 0.6000, 0.8836])

Reshape to 3x2x2: 
tensor([[[0.9669, 0.2515],
         [0.4714, 0.4307]],

        [[0.0537, 0.7649],
         [0.6509, 0.5877]],

        [[0.9159, 0.8122],
         [0.6000, 0.8836]]])

Reshape thanh kich thuoc 2x6: 
tensor([[0.9669, 0.2515, 0.4714, 0.4307, 0.0537, 0.7649],
        [0.6509, 0.5877, 0.9159, 0.8122, 0.6000, 0.8836]])

So phan tu ban dau:  12

So phan tu sau khi reshape 3x2x2:  12

So phan tu sau khi reshape 2x6:  12


## Nhận xét:
- tensor ban đầu 3x4 là 12
- sau khi reshape 3x2x2 là 12
- sau khi reshape 2x6 là 12
- vậy reshape chỉ thay đổi hình dạng của tensor chứ không thay đổi tổng số phần tử

# Bài 6: Phép toán và nhân ma trận

In [19]:
a= torch.randn(2,3)
b= torch.randn(2,3)
print("a: ")
print(a)
print("\nb: ")
print(b)
print("\na + b: ")
print(a+b)
print("\na / b: ")
print(a/b)
print("\na^2: ")
print(a**2)
print("\nmatrix multiplication( a@b.T): ")
print(a @ b.T)

print("\nshape cua a@b.T : ")
print((a@b.T).shape)

a: 
tensor([[-0.0315,  0.7685,  0.6521],
        [-0.6418,  1.1502,  0.6152]])

b: 
tensor([[ 0.4088,  0.1036, -0.3981],
        [ 0.8875,  0.7063,  0.6718]])

a + b: 
tensor([[0.3773, 0.8721, 0.2540],
        [0.2457, 1.8565, 1.2869]])

a / b: 
tensor([[-0.0771,  7.4209, -1.6379],
        [-0.7231,  1.6284,  0.9157]])

a^2: 
tensor([[9.9306e-04, 5.9063e-01, 4.2517e-01],
        [4.1192e-01, 1.3230e+00, 3.7842e-01]])

matrix multiplication( a@b.T): 
tensor([[-0.1929,  0.9529],
        [-0.3881,  0.6561]])

shape cua a@b.T : 
torch.Size([2, 2])


## Nhận xét:
- phép toán a*b là nhân từng phần tử tương ứng
- phép toán a@b.T là nhân ma trận 
- với a có kích thước 2x3 còn b.T có kích thước 3x2, nên shape của kết quả a@b.T là 2x2


# Bài 7: Các hàm thống kê trên Tensor

In [21]:
a= torch.randn(3,4)
print(a)
print("\nMean: ")
print(torch.mean(a, dim=0))

print("\nStandard deviation: ")
print(torch.std(a, dim=0))

print("\nCumulative sum: ")
print(torch.cumsum(a, dim=0))


print("\nMean: ")
print(torch.mean(a, dim=1))

print("\nStandard deviation: ")
print(torch.std(a, dim=1))

print("\nCumlative sum: ")
print(torch.cumsum(a, dim=1))

tensor([[ 1.7565, -1.4131, -0.0928, -0.8780],
        [-0.5116, -0.5934,  1.1568, -1.6289],
        [-0.1304, -0.8119,  0.0238, -1.2729]])

Mean: 
tensor([ 0.3715, -0.9395,  0.3626, -1.2599])

Standard deviation: 
tensor([1.2145, 0.4245, 0.6903, 0.3756])

Cumulative sum: 
tensor([[ 1.7565, -1.4131, -0.0928, -0.8780],
        [ 1.2449, -2.0066,  1.0640, -2.5069],
        [ 1.1145, -2.8185,  1.0878, -3.7798]])

Mean: 
tensor([-0.1569, -0.3943, -0.5479])

Standard deviation: 
tensor([1.3861, 1.1523, 0.6046])

Cumlative sum: 
tensor([[ 1.7565,  0.3434,  0.2506, -0.6274],
        [-0.5116, -1.1051,  0.0518, -1.5772],
        [-0.1304, -0.9423, -0.9185, -2.1914]])


## Nhận xét:
- dim=0 thực hiện theo chiều đầu tiên nên kết quả thống kê theo từng cột
- dim=1 thực hiện theo chiều thứ 2 nên kết quả thống kê theo từng hàng
- khi đổi dim=0 sang dim=1, phép tính thực hiện theo chiều khác nhau nên kết quả chuyển từ thống kê theo cột sang thống kê theo hàng

# Bài 8: Autograd cơ bản

In [2]:
x= torch.tensor(
    3.6,
    requires_grad=True
)
y= x*x
y.backward()

print("x= ", x)
print("y= ", y)
print("x.grad= ", x.grad)

x=  tensor(3.6000, requires_grad=True)
y=  tensor(12.9600, grad_fn=<MulBackward0>)
x.grad=  tensor(7.2000)


# Bài 9: Gradient Descent tìm hệ số đa thức

# Bài 10: Giải hệ phương trình bằng Autograd 

# Bài 11:  Viết chương trình PyTorch để thực hiện các yêu cầu sau: 
• Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4. 
• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột. 
• Cho y = 2x² + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công. 
• Thay đa thức trong Bài 9 bằng y = 2x² - 3x + 5; huấn luyện và cho biết các hệ số tìm được. 